In [2]:

import numpy as np
#creating 1-D array
a=np.array([1,2,3,4,5])
print(a)
# creating 2-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
d=np.zeros((2,2))
print(d)
#adding two arrays
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)
#multiply two arrays
d=np.array([[1,2],[3,4]])
e=np.array([[5,6],[7,8]])
f=d*e
print(f)
#matrix multiplication
d=np.array([[1,2],[3,4]])
e=np.array([[5,6],[7,8]])
i=np.dot(d,e)
print(i)

 

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[0. 0.]
 [0. 0.]]
[5 7 9]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
